replicaCount: 1
mysql:
  name: mysql
  group: db
  container:
    image: mysql:5.6
    port: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: flaskapi-secrets
          key: db_root_password 
  service:
    type: ClusterIP
    port: 3306
  volume:
    name: mysql-pv-claim
    kind: PersistentVolumeClaim
    mountPath: /var/lib/mysql
    pvc:
      name: mysql-pv
      accessMode: ReadWriteOnce
      storage: 5Gi
